branch-defaults:
  default:
    environment: chefalexa-api-dev
    group_suffix: null
global:
  application_name: chefalexa-api
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: null
